created config file, implemented directory check + image persistence

diff --git a/scripts/makePhotoV3 b/scripts/makePhotoV3
--- a/scripts/makePhotoV3
+++ b/scripts/makePhotoV3
@@ -1,27 +1,53 @@
 #!/bin/bash
 
+source config
+
 config() {
-	cam_width=1280
-	cam_height=1024
-	cam_hflip=1
-	cam_vflip=1
-	save_path=/home/pi/Pictures/growing #todo: make sure this directory exists and is writable
-	img_file='temp.jpg'
+	cam_width=${width:-1280}
+	cam_height=${height:-1024}
+	cam_hflip=${hflip:-1}
+	cam_vflip=${vflip:-1}
+	save_path=${path:-$PWD/photos}
+	img_name=${name:-"temp.jpg"}
+	persistence=${persistence:-true}
 }
 
 main() {
-	local now save_path
+	local now save_path persistence
 	config
 
-	now=$(date +"%Y-%m-%d_%H%M")
+
+  if [ ! -d "${save_path}" ]; then
+      mkdir -p "${save_path}"
+  fi
 
 	##CameraV3
 	/usr/bin/libcamera-jpeg --width ${cam_width} --height ${cam_height} --hflip ${cam_hflip} --vflip ${cam_vflip} -n --hdr -o "${save_path}/${img_file}"
-
 	./transmitPhoto "${save_path}/${img_file}"
 
-	#Rename last photo #todo: make persistence configurable
-	/bin/mv "${save_path}/${img_file}" "${save_path}/${now}.jpg"
+
+if [ $? = 0 ]; then
+
+  if [ "${persistence}" = true ]; then
+    persist
+  fi
+
+else
+  echo "smth went wrong"
+  #todo: implement retry handling, show error to user
+fi
+
+}
+
+persist()
+{
+  local file
+  now=$(date +"%Y-%m-%d_%H:%M:%S")
+
+  file="${save_path}/${now}.jpg"
+  /bin/mv "${save_path}/${img_name}" "${file}"
+
+  echo "Image persisted at ${file}"
 }
 
 main "$@"
